---
title: "viz"
output: html_document
date: '2022-06-16'
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(ggrepel)
library(ggplot2)
library(dplyr)
library(readr)
library(forcats)
library(broom)
library(geojsonio)
library(RColorBrewer)
library(rgeos)
options(scipen = 999)
```

# Home Tab

```{r}
states <- read_csv("data/states.csv")
state_bubble <- read_csv("data/states.csv") %>% select(state, lib_rev_ratio) %>% 
    mutate(lib_rev_ratio = round(lib_rev_ratio)) %>% 
    rename(State = state, `Liability-Renenue Ratio` = lib_rev_ratio) 
  
  city_bubble <- read_csv("data/cities.csv") %>% select(state, city, lib_rev_ratio) %>% 
    mutate(lib_rev_ratio = round(lib_rev_ratio)) %>% 
    rename(City = city, `Liability-Renenue Ratio` = lib_rev_ratio)
  
  county_bubble <- read_csv("data/counties.csv") %>% arrange(desc(population)) %>% slice(1:100) %>% 
    select(state, name, lib_rev_ratio) %>% 
    mutate(lib_rev_ratio = round(lib_rev_ratio)) %>% 
    rename(County = name, `Liability-Renenue Ratio` = lib_rev_ratio) 
  
  all_entities_liab_rev_ratio <- ggplotly(state_bubble %>% 
    ggplot(aes(State, `Liability-Renenue Ratio`)) +
    geom_point(color = "purple", size = 10, alpha = .2, show.legend = TRUE) +
    
    geom_point(aes(City, `Liability-Renenue Ratio`),
               data = city_bubble, color = "#E7B800", size = 10, alpha = .2) +
    
    geom_point(aes(County, `Liability-Renenue Ratio`),
               data = county_bubble, color = "#00AFBB", size = 10, alpha = .2) +
    labs(
      x = "",
      y = "") +
    scale_y_continuous(labels = scales::percent_format(suffix = "%", scale = 1)) +
    
    theme(axis.text.x  = element_text(color="white"),
          axis.ticks = element_blank(),
          panel.background = element_blank()
        
    )) 
  saveRDS(all_entities_liab_rev_ratio, "all_entities_liab_rev_ratio.RDS")
  #ggplotly(liab_rev_ratio_allentities)
```

```{r}
# These numbers are produce in gov_fin project. 
pie_df <- tribble(~x, ~"label_liabilities_type", ~"value2",
"1","Bonds and Notes",2554348758195,
"2","Loans",89172550650,
"3","Pensions",1671845182218,
"4","Leases",52877771988,
"5","Other Post-Employment Benefits",1270269047952,
"6","All Other",1384275002941
       ) %>% 
  select(-x) %>% 
  mutate(prop = round(value2/sum(value2),3)*100)

liabilities_by_type_pie <- pie(pie_df$value2, labels = paste0(pie_df$label_liabilities_type, "\n ",pie_df$prop,"%"), border = "white",
    col = brewer.pal(6, "Set2"),
    main = "Liabilities by Type (Fiscal Year 2020)")

pie_df2 <- tribble(~x, ~"label_state_local", ~"value",
"1","States",2530983274594,
"2","Cities and Towns",1239179537814,
"3","Counties",591455603771,
"4","Special Districts",1130012238813,
"5","Education",1175789650248,
"6","All Other",355368008704
) %>% select(-x) %>% mutate(prop = round(value/sum(value), 3)*100)


pie(pie_df2$value, labels = paste0(pie_df2$label_state_local, "\n ",pie_df2$prop,"%"), border = "white",
    col = brewer.pal(6, "Pastel1"),
    main = "Liabilities by Government Category (Fiscal Year 2020)")

```


# Analysis Tab

## States
```{r}
#data
topstates_liabilities <- states %>% arrange(desc(lib_rev_ratio)) %>% slice(1:10)
bottomstate_liabilities <- states %>% arrange(lib_rev_ratio) %>% slice(1:10)

top10_bottom10_states <- topstates_liabilities %>% rbind(bottomstate_liabilities) %>% 
  mutate(state = fct_reorder(state, lib_rev_ratio)) %>% 
  
#layer 1
    ggplot(aes(state, lib_rev_ratio)) +
  geom_segment(aes(x = state, xend = state, y = 0, yend = lib_rev_ratio), color = "grey") +
  geom_point(aes(state, lib_rev_ratio), color = "orange", size = 10) +
#layer2 
  geom_text(aes(label = round(lib_rev_ratio)), color = "white", size = 4) +
  
  # base
  geom_hline(yintercept = round(mean(states$lib_rev_ratio)),
             linetype = "dashed", color = "#a63e37", size = .3) +
  annotate(geom = "text", x = 1, y = 100, label = paste("Mean"), color = "#a63e37") +
  
    geom_hline(yintercept = round(median(states$lib_rev_ratio)),
             linetype = "dashed", color = "#377da6", size = .3) +
    annotate(geom = "text", x = 1, y = 60, label = paste("Median"), color = "#377da6") +
  #theme
  theme_minimal() +
  labs(
    x = "",
    y = "Ratio",
    title = "States governments with lowest and highest ratios of liabilities to revenue",
    subtitle = "",
    caption = "Note: Mean and median are values of all 50 states and DC")  +
  theme(axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle = 30)) 


# states %>% 
#   mutate(rank_lib_rev_ratio = rank(-lib_rev_ratio),
#          rank_population = rank(-population),
#          rank_total_liabilities = rank(-total_liabilities),
#          rank_revenue = rank(-revenue)
#          ) %>% 
#   arrange(rank_population) -> states_ranking

#write_csv(states, "states.csv")
```


```{r state map}
spdf <- geojson_read("data/us_states_hexgrid.geojson",  what = "sp")
spdf@data = spdf@data %>% mutate(google_name = gsub(" \\(United States\\)", "", google_name))

data <- states %>% select(state, lib_rev_ratio)

spdf_fortified <- tidy(spdf, region = "google_name") %>% 
  left_join(., data, by = c("id" = "state"))

# binning
spdf_fortified$bin <- cut(spdf_fortified$lib_rev_ratio, 
                           breaks=1, include.lowest = TRUE, labels=c())

# Pcolor scale coming from the viridis color palette
my_palette <- rev(magma(12))[c(-1,-8)]
 
# Calculate the centroid of each hexagon to add the label:
centers <- cbind.data.frame(data.frame(gCentroid(spdf, byid=TRUE), id=spdf@data$iso3166_2))

state_map_ratio <- ggplot() +
  geom_polygon(data = spdf_fortified, aes(fill = bin, x = long, y = lat, group = group) , size=0, alpha=0.9) +
  geom_text(data=centers, aes(x=x, y=y, label=id), color="white", size=3, alpha=0.6) +
  theme_void() +
  scale_fill_manual( 
    values=my_palette, 
    name="Liabilities-to-revenue Ratio", 
    guide = guide_legend( keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), label.position = "bottom", title.position = 'top', nrow=1) 
  ) +
  ggtitle( "" ) +
  theme(
    legend.position = c(0.5, 1.1),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size= 50, hjust=0.5, color = "#a61c00", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
  )
```


## Counties

```{r}
library(viridis)
#counties
counties <- read_csv("data/counties.csv") %>% 
  filter(lib_rev_ratio != Inf & state != "Puerto Rico")

counties %>% 
  arrange(desc(lib_rev_ratio)) %>% slice(1:5) -> top_counties 

counties_chart <- counties %>% 
  filter(lib_rev_ratio != Inf & state != "Puerto Rico") %>% 
  ggplot(aes(population, lib_rev_ratio)) +
  geom_point(aes(size = population), color = "cornflowerblue", alpha = .3) +
  
    # add lines 
  geom_hline(yintercept = round(mean(counties$lib_rev_ratio)),
             linetype = "dashed", color = "#a63e37", size = .5) +
    annotate(geom = "text", x = 5000000, y = 60, label = paste("Mean = ", round(mean(counties$lib_rev_ratio)))) +
  
  # top ones
  geom_point(aes(population, lib_rev_ratio), 
             data = top_counties,
             color = "#a63e37") +
  
    geom_text_repel(aes(label = name), data = top_counties,
                    nudge_y = 0.1, nudge_x = 0.1, segment.curvature = -0.1, color = "#a63e37", size = 6) +
  
  
  scale_x_log10() + 
  scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") +
  #scale_color_viridis(option = "H") +
  labs(
    x = "Population (log scale)",
    y = "Ratio",
    title = "Ratios of Liabilities to Revenue in County Governements",
    subtitle = "", 
    caption = "Note: Excluding Puerto Rico") +
  guides(size = FALSE) +
  theme_minimal() 

saveRDS(counties_chart, "counties_chart.RDS")

# counties %>% 
#   mutate(rank_lib_rev_ratio = rank(-lib_rev_ratio),
#          rank_population = rank(-population),
#          rank_total_liabilities = rank(-total_liabilities),
#          rank_revenue = rank(-revenue)
#          ) %>% 
#   arrange(rank_population) -> counties_ranking

#write_csv(counties_ranking, "counties_ranking.csv")
```



## Cities 

```{r}
fisc_50cities <- rio::import("data/FiSC 50 Cities Final.xlsx", sheet = "Chart Data")
fisc_50cities_chart <- ggplotly(fisc_50cities %>% 
               #filter(Population <=2000000) %>% 
               ggplot(aes(Population, `Total General Revenue (with exclusions) 2020`, text = City)) +
               geom_point(color = "orange") +
               
               geom_point(aes(size =`General Revenue to Per Capita Income Ratio`), color = "#A6D753", alpha = .4) +
               #scale_x_continuous(breaks = c(600000, 900000, 1200000, 1500000), 
               #                   labels = c("600K", "900K", "1.2M", "1.5M")) +
               #scale_y_continuous(breaks = c(3000000000, 6000000000, 9000000000),
                #                  labels = c( "$3B", "$6B", "$9B"))+
               guides(size = "none") +
              scale_x_log10()+
               
  
               labs(title = "Total General Revenue by Population in 50 Cities", 
                    caption = "Note: Outer cirles represent General Revenue to Per Capita Income Ratio") +
               
               theme_minimal() +
               theme(legend.title = element_blank(),
                     legend.position = "bottom"))
saveRDS(fisc_50cities_chart, "fisc_50cities_chart.RDS")
```

```{r}
top4_cities <- fisc_50cities %>% 
    filter(Population > 2000000) %>% 
    pivot_longer(cols = c(`Per Capita General Revenue excluding Grants`, `General Revenue Adjusted for Cost of Living Index`),
                 names_to = "Per Capita Revenue", 
                 values_to = "value") %>% 
    ggplot(aes(value, City, fill = `Per Capita Revenue`)) +
    
    geom_col(width = c(0.8, 0.5)) +
    scale_fill_manual(values = c("#E17D85", "#8EA0CB")) +
    
    geom_vline(xintercept = 6482.832, color = "#8EA0CB") +
    annotate("text", label = "Mean of 50 cities", x= 7100, y = 1.5, color = "#8EA0CB") +
    
    geom_vline(xintercept = 5949.024, color = "#E17D85") +
    annotate("text", label = "Mean of 50 cities adjusted", x = 6900, y = 2, color = "#E17D85")+
    
    labs(title = "Per Capital General Revenue in the 4 Most Populated Cities",
         y = "", 
         x = "USD") +
    theme_minimal() +
    theme(panel.grid.major.y = element_blank(),
          legend.title = element_blank(),
          legend.position = "bottom")
```

```{r}
fisc_cities_less2Mpop_chart <- ggplotly(fisc_50cities %>% 
               filter(Population <=2000000) %>% 
               ggplot(aes(Population, `Total General Revenue (with exclusions) 2020`, text = City)) +
               geom_point(color = "orange") +
               
               geom_point(aes(size =`General Revenue to Per Capita Income Ratio`), color = "#A6D753", alpha = .4) +
               scale_x_continuous(breaks = c(600000, 900000, 1200000, 1500000), 
                                  labels = c("600K", "900K", "1.2M", "1.5M")) +
               scale_y_continuous(breaks = c(3000000000, 6000000000, 9000000000),
                                  labels = c( "$3B", "$6B", "$9B"))+
               guides(size = "none") +
               scale_x_log10()+
  
               labs(title = "Total General Revenue by Population in Cities < 2M Population", 
                    caption = "Note: Outer cirles represent General Revenue to Per Capita Income Ratio") +
               
               theme_minimal() +
               theme(legend.title = element_blank(),
                     legend.position = "bottom"))
```



```{r}
cities <- read_csv("data/cities.csv")
region <- data.frame(state.name, state.region) %>% rename(state = state.name)

top_liab_rev_ratio <- cities %>% arrange(desc(lib_rev_ratio)) %>% slice(1:4)
bottom_liab_ratio <- cities %>% arrange(lib_rev_ratio) %>% slice(1:4)

top100_cities_ratio <- cities %>% left_join(region) %>% 
  ggplot(aes(population, lib_rev_ratio)) +
  geom_point(aes(size = population, color = state.region), alpha = .5) +
    # add lines 
  geom_hline(yintercept = round(mean(cities$lib_rev_ratio)),
             linetype = "dashed", color = "gray", size = .5) +
    annotate(geom = "text", x = 6000000, y = 200, label = paste("Mean = ", round(mean(cities$lib_rev_ratio)))) +
  # top 4
  geom_text_repel(aes(label = city),
                  data = top_liab_rev_ratio, 
                  nudge_y = 0.1, nudge_x = 0.15, segment.curvature = -0.1) +
  # bottom 4
  geom_text_repel(aes(label = city), 
                  data = bottom_liab_ratio,
                  nudge_y = 0.1, nudge_x = 0.1, segment.curvature = -0.1) +
  scale_x_log10() +
  scale_fill_viridis(discrete=TRUE, guide=FALSE, option="A") +
  theme_minimal() +
  labs(
    x = "Population (log scale)",
    y = "Ratio",
    title = "Ratios of Liabilities to Revenue in top 100 Cities",
    subtitle = "") +
 guides(size = FALSE, color = guide_legend("Region")) +
  theme(legend.position = "bottom")

saveRDS(top100_cities_ratio, "top100_cities_ratio.RDS")
```





```{r}
sd(cities$lib_rev_ratio) # 90.12852

# Components in top 4 cities: Chicago, IL, Houston, TX, Atlanta, GA and Dallas, TX
top_liab_rev_ratio

acfrs_city_pop_added_char <- readRDS("data/acfrs_city_pop_added_char.RDS")

acfrs_city_pop_added_char %>% 
  filter(name %in% top_liab_rev_ratio$city) %>% slice(1:4) 


cities_ranking <- cities %>% arrange(desc(population)) %>% select(-c(lat, long)) %>% 

  mutate(rank_lib_rev_ratio = rank(-lib_rev_ratio),
         rank_population = rank(-population),
         rank_total_liabilities = rank(-total_liabilities),
         rank_revenues = rank(-revenues)
         ) %>% 
  arrange(rank_population)

mean(cities$lib_rev_ratio)

write_csv(cities_ranking, "cities_ranking.csv")
```


## Districts
```{r}
districts <- read_csv("districts.csv")

district_ranking <- districts %>% select(-c(lat, lon, id)) %>% 
 mutate(rank_lib_rev_ratio = rank(-lib_rev_ratio),
         rank_total_liabilities = rank(-total_liabilities),
         rank_revenues = rank(-revenues)
         ) %>%  # Seattle School District No.1 should be the lowest?
arrange(rank_lib_rev_ratio)

write_csv(district_ranking, "district_ranking.csv")
```


```{r}

# Find number of employees in Seattle School District 1 and total number in all school districts in Washington
#https://www.census.gov/data/datasets/2020/econ/apes/annual-apes.html. Use the zip file
employees <- rio::import("data/20emp.xlsx")

employees %>% filter(State == "Washington" & `Type of Government` == "Independent School District") %>% 
 # filter(`Name of Government` == "Seattle School District 1") # Full-time Employees = 5328
  filter(str_detect(`Government Function`, "Total")) %>% 
  mutate(tot_school_dist = sum(`Full-time Employees`)) # total number in state WA 96124

(5328/96124) * 5983159000 = 331636960
  
# PENSION: 295,248,620 (in ACFRs portal)

# Adjusted total liability 
331636960 + 123970331 + 295248620 = 750855911

# Adjusted liability-revenue Ratio: 
(750855911/1263718387)*100	= 59.4164

```



# Data Tab 
## States

```{r}
acfrs <- readRDS("data/data_from_dbsite.RDS")

# All 52 state governments 
acfrs %>% select(state, name, category, total_liabilities, bonds_outstanding, net_pension_liability, compensated_absences, revenues) %>% 
  filter(category == "General Purpose") %>% 
  filter(str_detect(name, "State of|Commonwealth")) %>% 
  filter(!str_detect(name, "Yap|Kosrae")) -> state_gov

each_state_gov <- state_gov %>% 
  filter(name == "State of Arizona") %>% 
  rename("Total Liabilities" = total_liabilities, 
         "Bond Oustanding" = bonds_outstanding, 
         "Net Pension Liability" = net_pension_liability, "Compensated Absences" = compensated_absences, 
         "Revenues" = revenues) %>% 
  pivot_longer(cols = 4:8,
               names_to = "indicator",
               values_to = "value") %>% 
  select(-c(state, category))

means_state_gov <- state_gov %>% 
  summarise("Total Liabilities" = mean(total_liabilities), 
            "Bond Oustanding" = mean(bonds_outstanding), 
            "Net Pension Liability" = mean(net_pension_liability), 
            "Compensated Absences" = mean(compensated_absences), 
            "Revenues" = mean(revenues)) %>%  
  pivot_longer(cols = 1:5, 
               names_to = "indicator",
               values_to = "value"
               ) %>% 
  mutate(name = "Mean Values of All State Governements")

```


```{r}
# Demonstrate 1 state, with comparison to mean values of the same type of entity
 each_state_gov %>% rbind(means_state_gov) %>% 

  ggplot(aes(indicator, value, fill = name)) +
  geom_bar(stat="identity", position = position_dodge(width = 0.5), alpha = .8) + # overlapping the bars half way
    
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) + #palette="Spectral"
  theme_minimal() +
  labs(title = "Comparison",
    x = "Indicator", 
    y = "Value"
  ) +
  theme(axis.text.x = element_text(hjust = 1, angle = 20),
        legend.title = element_blank(),
        legend.position = c(.3, .8)) -> comparison_state_mean_state_gov
 
saveRDS(comparison_state_mean_state_gov, "comparison_state_mean_state_gov.RDS")
```

